{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d1d34f74-39c0-4ad2-84c7-4ac342216d1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import asyncio\n",
    "import aiohttp\n",
    "#sys.path.append('/Users/andreas/fun/useful_py_func/pyTibber/tibber/')\n",
    "sys.path.append('/home/andram/fun/LED-env/lib/python3.11/site-packages/tibber')\n",
    "from tibber import Tibber, gql_queries\n",
    "import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "06d94246",
   "metadata": {},
   "outputs": [],
   "source": [
    "async def main():\n",
    "    TOKEN = \"U4L8yS_OHsfgKndAhNQZ8K-JYElbNUagYvToCF3ZPVE\"\n",
    "    try:\n",
    "        # Initialize Tibber connection\n",
    "        tibber_connection = Tibber(access_token=TOKEN)\n",
    "        await tibber_connection.update_info()\n",
    "\n",
    "        # Retrieve the websocketSubscriptionUrl\n",
    "        if tibber_connection.realtime.sub_endpoint:\n",
    "            print(\"WebSocket Subscription URL:\", tibber_connection.realtime.sub_endpoint)\n",
    "\n",
    "        # Get hourly PriceRating and PriceLevel for each active home\n",
    "        for home_id in tibber_connection.get_home_ids(only_active=True):\n",
    "            home = tibber_connection.get_home(home_id)\n",
    "            if home is not None:\n",
    "                await home.update_price_info()\n",
    "                if home.current_price_info:\n",
    "                    price_info = home.current_price_info\n",
    "                    print(f\"Home ID: {home_id}\")\n",
    "                    print(f\"Hourly PriceRating: {price_info['total']}\")\n",
    "                    print(f\"PriceLevel: {price_info['priceLevel']}\")\n",
    "                    \n",
    "        # Closing the connection\n",
    "        await tibber_connection.close_connection()\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {e}\")\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c46fde0f-1a72-45ad-912c-0b36d4725efe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'viewer': {'home': {'currentSubscription': {'priceRating': {'daily': {'entries': []}}}}}}\n"
     ]
    }
   ],
   "source": [
    "async def main():\n",
    "    TOKEN = \"U4L8yS_OHsfgKndAhNQZ8K-JYElbNUagYvToCF3ZPVE\"\n",
    "    USER_AGENT = \"LED_client\"\n",
    "    HOME_ID = \"975996b6-e7ca-4fbf-9f72-61e2df95bc0c\"\n",
    "    tibber_connection = Tibber(access_token=TOKEN,user_agent=USER_AGENT)\n",
    "    await tibber_connection.update_info()\n",
    "\n",
    "\n",
    "    # GraphQL query to fetch home information\n",
    "    query_type = \"daily\"  # or \"daily\", \"monthly\" depending on your need\n",
    "    query = gql_queries.HISTORIC_PRICE.format(HOME_ID, query_type)\n",
    "\n",
    "    #query = gql_queries.PRICE_INFO % HOME_ID\n",
    "\n",
    "    data = await tibber_connection.execute(query)\n",
    "    if data:\n",
    "        print(data)\n",
    "        #print(data['viewer']['home']['currentSubscription']['priceInfo']['current'])\n",
    "    else:\n",
    "        print('No data')\n",
    "\n",
    "\n",
    "    await tibber_connection.close_connection()\n",
    "await main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "322445db",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Watchdog: Connection is down, 2024-01-26 15:41:08.376000+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 39\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 655, in __await_impl_timeout__\n",
      "    return await self.__await_impl__()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n",
      "    await protocol.handshake(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 323, in handshake\n",
      "    status_code, response_headers = await self.read_http_response()\n",
      "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 139, in read_http_response\n",
      "    status_code, reason, headers = await read_response(self.reader)\n",
      "                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/http.py\", line 120, in read_response\n",
      "    status_line = await read_line(stream)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/http.py\", line 194, in read_line\n",
      "    line = await stream.readline()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/streams.py\", line 565, in readline\n",
      "    line = await self.readuntil(sep)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/streams.py\", line 657, in readuntil\n",
      "    await self._wait_for_data('readuntil')\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/streams.py\", line 542, in _wait_for_data\n",
      "    await self._waiter\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 151, in _watchdog\n",
      "    await self.sub_manager.connect_async()  # type: ignore\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/client.py\", line 789, in connect_async\n",
      "    await self.transport.connect()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/transport/websockets_base.py\", line 490, in connect\n",
      "    self.websocket = await asyncio.wait_for(\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 519, in wait_for\n",
      "    async with timeouts.timeout(timeout):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/timeouts.py\", line 115, in __aexit__\n",
      "    raise TimeoutError from exc_val\n",
      "TimeoutError\n",
      "Watchdog: Connection is down, 2024-01-27 13:20:14.938686+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 40\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 151, in _watchdog\n",
      "    await self.sub_manager.connect_async()  # type: ignore\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/client.py\", line 789, in connect_async\n",
      "    await self.transport.connect()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/transport/websockets_base.py\", line 490, in connect\n",
      "    self.websocket = await asyncio.wait_for(\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 655, in __await_impl_timeout__\n",
      "    return await self.__await_impl__()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n",
      "    await protocol.handshake(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 329, in handshake\n",
      "    raise InvalidStatusCode(status_code, response_headers)\n",
      "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429\n",
      "Watchdog: Connection is down, 2024-01-27 17:20:40.086651+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 41\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 152, in _watchdog\n",
      "    await self._resubscribe_homes()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 173, in _resubscribe_homes\n",
      "    await asyncio.gather(*[home.rt_resubscribe() for home in self._homes])\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/home.py\", line 449, in rt_resubscribe\n",
      "    await asyncio.gather(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/home.py\", line 199, in update_info\n",
      "    if data := await self._tibber_control.execute(UPDATE_INFO % self._home_id):\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/__init__.py\", line 102, in execute\n",
      "    resp = await self.websession.post(API_ENDPOINT, **post_args, timeout=self.timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/aiohttp/client.py\", line 421, in _request\n",
      "    raise RuntimeError(\"Session is closed\")\n",
      "RuntimeError: Session is closed\n",
      "Watchdog: Connection is down, 2024-01-27 17:40:45.330765+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 42\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 151, in _watchdog\n",
      "    await self.sub_manager.connect_async()  # type: ignore\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/client.py\", line 789, in connect_async\n",
      "    await self.transport.connect()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/transport/websockets_base.py\", line 490, in connect\n",
      "    self.websocket = await asyncio.wait_for(\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 655, in __await_impl_timeout__\n",
      "    return await self.__await_impl__()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n",
      "    await protocol.handshake(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 329, in handshake\n",
      "    raise InvalidStatusCode(status_code, response_headers)\n",
      "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429\n",
      "Watchdog: Connection is down, 2024-01-28 18:20:46.283371+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 43\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 151, in _watchdog\n",
      "    await self.sub_manager.connect_async()  # type: ignore\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/client.py\", line 789, in connect_async\n",
      "    await self.transport.connect()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/transport/websockets_base.py\", line 490, in connect\n",
      "    self.websocket = await asyncio.wait_for(\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 655, in __await_impl_timeout__\n",
      "    return await self.__await_impl__()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n",
      "    await protocol.handshake(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 329, in handshake\n",
      "    raise InvalidStatusCode(status_code, response_headers)\n",
      "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429\n",
      "Watchdog: Connection is down, 2024-01-28 18:40:51.574739+00:00\n",
      "Error in watchdog connect, retrying in 1200 seconds, 44\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/tibber/realtime.py\", line 151, in _watchdog\n",
      "    await self.sub_manager.connect_async()  # type: ignore\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/client.py\", line 789, in connect_async\n",
      "    await self.transport.connect()\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/gql/transport/websockets_base.py\", line 490, in connect\n",
      "    self.websocket = await asyncio.wait_for(\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/asyncio/tasks.py\", line 520, in wait_for\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 655, in __await_impl_timeout__\n",
      "    return await self.__await_impl__()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 662, in __await_impl__\n",
      "    await protocol.handshake(\n",
      "  File \"/Users/andreas/miniconda3/envs/pyTibber/lib/python3.12/site-packages/websockets/legacy/client.py\", line 329, in handshake\n",
      "    raise InvalidStatusCode(status_code, response_headers)\n",
      "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429\n"
     ]
    }
   ],
   "source": [
    "ACCESS_TOKEN = \"U4L8yS_OHsfgKndAhNQZ8K-JYElbNUagYvToCF3ZPVE\"\n",
    "USER_AGENT = \"LED_client_1\"\n",
    "\n",
    "def _callback(pkg):\n",
    "    data = pkg.get(\"data\")\n",
    "    print(\"Real-time data received:\", pkg)\n",
    "    print(data)\n",
    "\n",
    "async def run():\n",
    "    async with aiohttp.ClientSession() as session:\n",
    "        tibber_connection = Tibber(ACCESS_TOKEN, websession=session, user_agent=USER_AGENT)\n",
    "        await tibber_connection.update_info()\n",
    "\n",
    "        # Fetching the WebSocket Subscription URL dynamically\n",
    "        query = '''\n",
    "        {\n",
    "          viewer {\n",
    "            homes {\n",
    "              id\n",
    "              address {\n",
    "                address1\n",
    "                city\n",
    "              }\n",
    "              owner {\n",
    "                name\n",
    "              }\n",
    "              currentSubscription {\n",
    "                priceInfo {\n",
    "                  current {\n",
    "                    total\n",
    "                    level\n",
    "                  }\n",
    "                }\n",
    "              }\n",
    "            }\n",
    "            websocketSubscriptionUrl\n",
    "          }\n",
    "        }\n",
    "\n",
    "        '''\n",
    "        data = await tibber_connection.execute(query)\n",
    "        if data:\n",
    "            websocket_url = data['viewer']['websocketSubscriptionUrl']\n",
    "            print(\"WebSocket Subscription URL:\", websocket_url)\n",
    "            print(data)\n",
    "            print(\"data:\", data['viewer']['homes'][1]['currentSubscription']['priceInfo']['current']['level'])\n",
    "\n",
    "        # Subscribing to real-time updates for the first home\n",
    "        home = tibber_connection.get_homes()[0]\n",
    "        home.update_info() # I want the _callback function to execute the home.update_info() function \n",
    "        await home.rt_subscribe(_callback)    \n",
    "\n",
    "        while True:\n",
    "            await asyncio.sleep(20)\n",
    "await run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6323391b",
   "metadata": {},
   "outputs": [],
   "source": [
    "ACCESS_TOKEN = \"U4L8yS_OHsfgKndAhNQZ8K-JYElbNUagYvToCF3ZPVE\"\n",
    "USER_AGENT = \"LED_client\"\n",
    "PRICE_QUERY_INTERVAL = 10  # Interval in seconds (e.g., 3600 seconds for hourly updates)\n",
    "\n",
    "def _callback(pkg):\n",
    "    print(\"Real-time data received:\", pkg)\n",
    "\n",
    "async def fetch_price_level(tibber_connection):\n",
    "    i = 0\n",
    "    query = '''\n",
    "    {\n",
    "      viewer {\n",
    "        homes {\n",
    "          currentSubscription {\n",
    "            priceInfo {\n",
    "              current {\n",
    "                level\n",
    "              }\n",
    "            }\n",
    "          }\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "    '''\n",
    "    while True:\n",
    "        i +=1\n",
    "        if i>= 3:\n",
    "            break\n",
    "        else:\n",
    "            print('i:',i)\n",
    "        \n",
    "        data = await tibber_connection.execute(query)\n",
    "        if data:\n",
    "            for home in data['viewer']['homes']:\n",
    "                if home.get('currentSubscription') and home['currentSubscription'].get('priceInfo'):\n",
    "                    current_price_info = home['currentSubscription']['priceInfo'].get('current')\n",
    "                    if current_price_info:\n",
    "                        print(f\"Current Price Level: {current_price_info['level']}\")\n",
    "        await asyncio.sleep(PRICE_QUERY_INTERVAL)\n",
    "\n",
    "async def run():\n",
    "    async with aiohttp.ClientSession() as session:\n",
    "        tibber_connection = Tibber(ACCESS_TOKEN, websession=session, user_agent=USER_AGENT)\n",
    "        await tibber_connection.update_info()\n",
    "\n",
    "        # Start the periodic task for fetching price level\n",
    "        asyncio.create_task(fetch_price_level(tibber_connection))\n",
    "        \n",
    "        while True:\n",
    "            await asyncio.sleep(10)\n",
    "\n",
    "await run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e279d8a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to Tibber as Erlend Thue\n",
      "API called: fetch price info.\n",
      "Delay for next update: 386 [s]\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import datetime as dt\n",
    "import aiohttp\n",
    "from tibber import Tibber, InvalidLoginError, FatalHttpExceptionError, RetryableHttpExceptionError\n",
    "\n",
    "class MicroBitCommunicator:\n",
    "    @staticmethod\n",
    "    async def update_micro_bit(price_level):\n",
    "        print(f\"Updating micro-bit with new price level: {price_level}\")\n",
    "        # Add code to send data to micro-bit.\n",
    "\n",
    "class TibberAPI:\n",
    "    MAX_RETRIES = 5\n",
    "\n",
    "    def __init__(self, access_token: str, user_agent: str = \"Tibber_Client_1\"):\n",
    "        self._access_token = access_token\n",
    "        self._user_agent = user_agent\n",
    "        self._tibber_connection = None\n",
    "        self.last_price_level = None\n",
    "        self.retry_count = 0\n",
    "\n",
    "    async def connect(self):\n",
    "        self._session = aiohttp.ClientSession()\n",
    "        self._tibber_connection = Tibber(self._access_token, websession=self._session, user_agent=self._user_agent)\n",
    "        while self.retry_count < self.MAX_RETRIES:\n",
    "            try:\n",
    "                await self._tibber_connection.update_info()\n",
    "                break\n",
    "            except Exception as e:\n",
    "                self.retry_count += 1\n",
    "                print(f\"Attempt {self.retry_count}/{self.MAX_RETRIES} failed: {e}\")\n",
    "                await asyncio.sleep(2 ** self.retry_count)  # Exponential back-off\n",
    "            if self.retry_count >= self.MAX_RETRIES:\n",
    "                print(\"Maximum retry attempts reached. Exiting.\")\n",
    "\n",
    "    async def close_connection(self):\n",
    "        if self._session:\n",
    "            await self._session.close()\n",
    "\n",
    "    async def fetch_price_info(self, home_id: str):\n",
    "        home = self._tibber_connection.get_home(home_id)\n",
    "        if home is None:\n",
    "            raise ValueError(f\"No Tibber home found with ID: {home_id}\")\n",
    "\n",
    "        while True:\n",
    "            try:\n",
    "                # Fetch immediately if the last price level is None\n",
    "                if self.last_price_level is None:\n",
    "                    await home.update_info()\n",
    "                    print(\"API called: fetch price info.\")\n",
    "                    if home.current_price_info:\n",
    "                        current_price_level = home.current_price_info.get('level')\n",
    "                        print(f\"Current Price Level for {home_id}: {current_price_level}\")\n",
    "                        if current_price_level != self.last_price_level:\n",
    "                            self.last_price_level = current_price_level\n",
    "                            await MicroBitCommunicator.update_micro_bit(current_price_level)\n",
    "                \n",
    "                # Calculate delay for the next hourly update\n",
    "                next_hour = dt.datetime.now(dt.timezone.utc).replace(minute=0, second=0, microsecond=0) + dt.timedelta(hours=1)\n",
    "                delay = (next_hour - dt.datetime.now(dt.timezone.utc)).total_seconds()\n",
    "                print(f\"Delay for next update: {round(delay)} [s]\")\n",
    "                await asyncio.sleep(delay)\n",
    "\n",
    "                # Fetch after the delay\n",
    "                await home.update_info()\n",
    "                print(\"API called: fetch price info.\")\n",
    "                if home.current_price_info:\n",
    "                    current_price_level = home.current_price_info.get('level')\n",
    "                    print(f\"Current Price Level for {home_id}: {current_price_level}\")\n",
    "                    if current_price_level != self.last_price_level:\n",
    "                        self.last_price_level = current_price_level\n",
    "                        await MicroBitCommunicator.update_micro_bit(current_price_level)\n",
    "            except Exception as e:\n",
    "                print(f\"Error in fetch_price_info: {e}\")\n",
    "                await asyncio.sleep(60)  # Wait a bit before retrying\n",
    "\n",
    "async def main():\n",
    "    access_token = \"U4L8yS_OHsfgKndAhNQZ8K-JYElbNUagYvToCF3ZPVE\"  \n",
    "    home_id = \"975996b6-e7ca-4fbf-9f72-61e2df95bc0c\"\n",
    "    tibber_api = TibberAPI(access_token)\n",
    "    await tibber_api.connect()\n",
    "    if tibber_api._tibber_connection:\n",
    "        print(f\"Connected to Tibber as {tibber_api._tibber_connection.name}\")\n",
    "        asyncio.create_task(tibber_api.fetch_price_info(home_id))\n",
    "        try:\n",
    "            while True:\n",
    "                await asyncio.sleep(60)\n",
    "        except KeyboardInterrupt:\n",
    "            print(\"Stopping the program...\")\n",
    "        await tibber_api.close_connection()\n",
    "\n",
    "await main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d44a0d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "    query = '''\n",
    "    {\n",
    "      viewer {\n",
    "        homes {\n",
    "          id\n",
    "          address {\n",
    "            address1\n",
    "            city\n",
    "          }\n",
    "          owner {\n",
    "            name\n",
    "          }\n",
    "          currentSubscription {\n",
    "            priceInfo {\n",
    "              current {\n",
    "                total\n",
    "                level\n",
    "              }\n",
    "            }\n",
    "          }\n",
    "        }\n",
    "        websocketSubscriptionUrl\n",
    "      }\n",
    "    }\n",
    "    '''\n",
    "\n",
    "\n",
    "            homes = data['viewer']['homes']\n",
    "        for home in homes:\n",
    "            print(f\"Home ID: {home['id']}\")\n",
    "            print(f\"Address: {home['address']['address1']}, {home['address']['city']}\")\n",
    "            print(f\"Owner's Name: {home['owner']['name']}\")\n",
    "\n",
    "            # Check if currentSubscription and priceInfo are not None\n",
    "            if home.get('currentSubscription') and home['currentSubscription'].get('priceInfo'):\n",
    "                current_price_info = home['currentSubscription']['priceInfo'].get('current')\n",
    "                if current_price_info:\n",
    "                    print(f\"Current Power Price: {current_price_info['total']}\")\n",
    "                    print(f\"Price Level: {current_price_info['level']}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pyTibber",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
